###
POST http://localhost:8080/v1/async/books
Content-Type: application/json

{
  "libraryEventId": 1,
  "book": {
    "bookId": 456,
    "bookName": "Kafka Book2",
    "bookAuthor": "Author Name"
  }
}

###
POST http://localhost:8080/v2/async/books
Content-Type: application/json

{
  "libraryEventId": 1,
  "book": {
    "bookId": 456,
    "bookName": "Kafka Book2",
    "bookAuthor": "Author Name"
  }
}

###
POST http://localhost:8080/v3/async/books
Content-Type: application/json

{
  "libraryEventId": 1,
  "book": {
    "bookId": 456,
    "bookName": "Kafka Book2",
    "bookAuthor": "Author Name"
  }
}

###

POST http://localhost:8080/v1/sync/books
Content-Type: application/json

{
  "libraryEventId": 1,
  "book": {
    "bookId": 456,
    "bookName": "Kafka Book",
    "bookAuthor": "Author Name"
  }
}

