apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka-bitnami
  template:
    metadata:
      labels:
        app: kafka-bitnami
    spec:
      containers:
        - name: kafka-bitnami
          image: bitnami/kafka:3.7.0
          ports:
            - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  type: NodePort
  ports:
    - port: 9092
  selector:
    app: app-nginx
