#
# Created by MikBac on 19.12.2022
#
version: "3.4"
services:
  kafka-broker-1:
    image: 'bitnami/kafka:3.4.0'
    hostname: bitnami-kafka-1
    restart: unless-stopped
    ports:
      - '9192:9092'
    volumes:
      - kafka-storage-1:/bitnami/kafka
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=EXTERNAL://:9092,CONTROLLER://:9093,INTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=EXTERNAL://localhost:9192,INTERNAL://bitnami-kafka-1:9094
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@bitnami-kafka-1:9093,2@bitnami-kafka-2:9093,3@bitnami-kafka-3:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=rwJnBJlxJUaYNBpgdpahcx
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1g
    networks:
      - kafka-network
  kafka-broker-2:
    image: 'bitnami/kafka:3.4.0'
    hostname: bitnami-kafka-2
    restart: unless-stopped
    ports:
      - '9292:9092'
    volumes:
      - kafka-storage-2:/bitnami/kafka
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=EXTERNAL://:9092,CONTROLLER://:9093,INTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=EXTERNAL://localhost:9292,INTERNAL://bitnami-kafka-2:9094
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@bitnami-kafka-1:9093,2@bitnami-kafka-2:9093,3@bitnami-kafka-3:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_KRAFT_CLUSTER_ID=rwJnBJlxJUaYNBpgdpahcx
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1g
    networks:
      - kafka-network
  kafka-broker-3:
    image: 'bitnami/kafka:3.4.0'
    hostname: bitnami-kafka-3
    restart: unless-stopped
    ports:
      - '9392:9092'
    volumes:
      - kafka-storage-3:/bitnami/kafka
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=EXTERNAL://:9092,CONTROLLER://:9093,INTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=EXTERNAL://localhost:9392,INTERNAL://bitnami-kafka-3:9094
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@bitnami-kafka-1:9093,2@bitnami-kafka-2:9093,3@bitnami-kafka-3:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_KRAFT_CLUSTER_ID=rwJnBJlxJUaYNBpgdpahcx
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1g
    networks:
      - kafka-network
  kouncil-ui:
    image: 'consdata/kouncil:1.4'
    restart: unless-stopped
    ports:
      - '9080:8080'
    environment:
      - bootstrapServers=bitnami-kafka-1:9094
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
    networks:
      - kafka-network
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3

volumes:
  kafka-storage-1:
    driver: local
  kafka-storage-2:
    driver: local
  kafka-storage-3:
    driver: local

networks:
  kafka-network:
